<a href="https://colab.research.google.com/github/SplitImages/website/blob/gh-pages/NumpyBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy Basic
#### 배열생성

In [ ]:
import numpy as np
# 1차원 배열 생성
a = np.array([1, 2, 3, 4])

# 2차원 배열 생성
b = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

# 3차원 배열 생성
c = np.array([[[ 0, 1, 2, 3],
           [ 4, 5, 6, 7],
           [ 8, 9, 10, 11]]])

### Numpy Array 속성
- ndim : ndarray의 차원을 나타냄
- shape : 각 차원의 ndarray 크기를 튜플 형태로 나타냄
- size : ndarray에있는 요소의 총 수
- dtype : ndarray의데이터 유형
   - uint8 ~ uint64, int8 ~ int64, float16 ~ float128, bool 등
- T : ndarray의 전치된 결과 반환 (행열 바꾸기)

In [5]:
### Numpy Array 속성
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
x.ndim

2

In [7]:
x.shape

(2, 3)

In [8]:
x.size

6

In [9]:
x.dtype

dtype('int64')

In [11]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# Numpy Indexing
- 특정행과 열에 접근: 넘파이배열[행, 열]
- :슬라이싱도 가능

In [14]:
### Numpy Array 접근 -> [행, 열]
x[0, 0]

1

In [15]:
x[:, 1:]

array([[2, 3],
       [5, 6]])

##### 배열생성함수
- arange 수의 범위를 만들어주는 함수
- linspace 수의 범위를 균일하게 나누고자 할 때 사용
- np.ones((행,열))   1로 채워진 배열생성
- np.zeros((행,열))  0으로 채워진 배열생성
- np.full((행,열), 값) 특정값으로 채워진 배열생성

In [ ]:
# 0 ~ 9 까지 값을 갖는 배열
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 0.1 ~ 1.0 까지 0.1씩 증가는 값을 갖는 배열 생성
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [17]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [25]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [26]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.ones((2,2))*-1
np.full((2,2),-1)

array([[-1, -1],
       [-1, -1]])

##### RandomSampling

In [ ]:
import numpy as np
np.random.seed(0)

a = np.array(np.arange(100))
np.random.choice(a, size=10, replace=False)  #비복원추출

array([26, 86,  2, 55, 75, 93, 16, 73, 54, 95])

In [39]:
import numpy as np
np.random.seed(0)

a = np.arange(100)
np.random.choice(a, size=10, replace=False)  #비복원추출
np.random.choice(a, size=10, replace=True)  #복원추출

array([34, 48, 93,  3, 98, 42, 77, 21, 73,  0])

In [44]:
# 동전던지기 10회 수행
np.random.seed(1)

a = np.arange(2)
np.random.choice(a, size = 10, replace = True)

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 0])

#### 난수생성방법
- np.random.rand : 0부터 1사이의 균일분포
- np.random.randn : 가우시안 표준 정규 분포
- np.random.randint : 균일 분포의 정수 난수

In [ ]:
np.random.randint(0, 100, 33)

array([34, 48, 93,  3, 98, 42, 77, 21, 73,  0, 10, 43, 58, 23, 59,  2, 98,
       62, 35, 94, 67, 82, 46, 99, 20, 81, 50, 27, 14, 41, 58, 65, 36])

In [47]:
# 로또 번호 추출 1-45중 6개
np.random.randint(1,46,6)

array([29, 30, 15,  5, 24, 24])

In [ ]:
np.random.randn(3,4)

array([[-0.20642094,  0.48842647, -0.83833097,  0.38116374],
       [-0.99090328,  1.01788005,  0.3415874 , -1.25088622],
       [ 0.92525075, -0.90478616,  1.84369153,  1.52550724]])

In [ ]:
np.random.randint(1,100,5)

array([67, 53, 68, 62, 15])